name: Autopath
version: '${project.version}'
main: me.TuxPenguinS.autopath.AutoPath
api-version: 1.13
commands:
  AutoPath:
    description: Enable or disable AutoPath
    usage: /<command>
    aliases: [autopath]
  AutoPathTerrain:
    description: Set block types for the terrain a path will be on.
    usage: /<command> [BLOCK 1] [BLOCK 2], ...
  AutoPathMaterial:
    description: Set block types for AutoPath
    usage: /<command> [BLOCK 1] [BLOCK 2] [BLOCK 3], ...